### ISSUE TITLE
教程分类

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/tutorials#20]

**Comment by 0xdwong** [comment]
需要添加一个语言(中/英)字段 @Oaciqihz

**Comment by 0xdwong** [comment]
需要添加一个媒体字段(文本/视频/音频) @Oaciqihz

**Comment by ccxdcyl** [comment]
@Oaciqihz 
UI样式：
https://lanhuapp.com/web/#/item/project/stage?pid=5d34e37a-97bf-4156-8bf8-8e2ccf6332b2&tid=76420b91-ae5e-40dc-b733-6334aad3f2b2&see=all
