### ISSUE TITLE
solidity教程中存在错误

### ISSUE THREAD

**Issue by Ryze-T** [decert-me/tutorials#50]
solidity教程中，Foundry开发框架-合约开发及编译段落中：
![image](https://github.com/decert-me/tutorials/assets/76553352/4213a189-8e07-42a2-95cf-a496efed4869)
默认生成的项目结构中是没有 contracts这个目录的，愿意应该是想表达src这个目录？

**Comment by liangjies** [comment]
Foundry默认智能合约目录为 `src` ，这里应该改为 `src`
@0xdwong

**Comment by Ryze-T** [comment]
还有一个错误：
![image](https://github.com/decert-me/tutorials/assets/76553352/331339bc-b0dc-410d-aeb2-34f4f5c06cee)
