### ISSUE TITLE
教程文档支持gitbook格式

### ISSUE THREAD

**Issue by 0xdwong** [decert-me/tutorials#9]

**Comment by panyinglei** [comment]
github地址：https://github.com/rootsongjc/kubernetes-handbook
gitbook地址：https://amdocs-1.gitbook.io/kubernetes-handbook/
这个项目编译的时候失败
![image](https://github.com/decert-me/tutorials/assets/58837426/9cff016f-4639-4190-8125-ba6d961151bc)

**Comment by panyinglei** [comment]
点击编辑此页，跳转的页面不正确
![image](https://github.com/decert-me/tutorials/assets/58837426/b9db96c9-102f-4f64-a27d-925ffe77e212)
![image](https://github.com/decert-me/tutorials/assets/58837426/b253b1f9-4118-4812-b8bf-2b2eeceb58e6)

**Comment by 0xdwong** [comment]
> github地址：https://github.com/rootsongjc/kubernetes-handbook gitbook地址：https://amdocs-1.gitbook.io/kubernetes-handbook/ 这个项目编译的时候失败 ![image](https://user-images.githubusercontent.com/58837426/245982997-9cff016f-4639-4190-8125-ba6d961151bc.png)

新建了一个Issue跟踪后续：https://github.com/decert-me/tutorials/issues/11

**Comment by 0xdwong** [comment]
see：https://github.com/decert-me/tutorials/pull/10
